/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$product-slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$product-slug',
  path: '/products/$product-slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/products/$product-slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$product-slug': typeof ProductsProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$product-slug': typeof ProductsProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$product-slug': typeof ProductsProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$product-slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$product-slug'
  id: '__root__' | '/' | '/products/$product-slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$product-slug': {
      id: '/products/$product-slug'
      path: '/products/$product-slug'
      fullPath: '/products/$product-slug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
